sudo: false
language: python
matrix:
  include:
  - os: linux
    python: "3.4"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.4
  - os: linux
    python: "3.5"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.5
  - os: linux
    python: "3.6"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['gcc-4.9', 'g++-4.9']
    env: CC=gcc-4.9 CXX=g++-4.9 PYTHON=3.6

before_install:
  - pip$PY install --upgrade pip setuptools wheel

install:
  - if [ "${PYTHON:0:1}" = "3" ]; then export PY=3; fi
  - pip$PY install -r requirements.txt
  - pip$PY install pytest
  - pip$PY install pytest-cov
  - pip$PY install coveralls

script: pytest src/psm --cov src/psm

after_success:
- coveralls